### ISSUE TITLE
Make the contracts upgradeable

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/standard-contracts#5]
Remove constructor, use initialize, instead.

**Comment by fadeev** [comment]
Add this to initialize:

>  I'm now thinking that with universal NFT/FT we can streamline the deploy process by adding universal contract address as one of the constructor parameters with deploying a connected contract. The idea is you should always deploy the universal contract first, because it's a single required component, and then deploy connected contracts. This way connected-set-universal task will no longer be required. It still makes sense to keep it as contract addresses may change, but you wouldn't need to set manually it after deploying a connected contract.

**Comment by lukema95** [comment]
@fadeev What other repos contracts need to be upgraded? Maybe I can take some.

**Comment by fadeev** [comment]
@lukema95 the PR above already takes care of this.

If you're looking for issues to contribute to, I recommend checking out https://github.com/zeta-chain/universalkit/issues/30 and https://github.com/zeta-chain/localnet/issues/54
